[project]
name = "microsoft_outlook_appointment_scheduling_assistant"
version = "0.1.2"
description = "microsoft_outlook_appointment_scheduling_assistant using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,litellm,tools]==1.8.0",
]

[project.scripts]
microsoft_outlook_appointment_scheduling_assistant = "microsoft_outlook_appointment_scheduling_assistant.main:run"
run_crew = "microsoft_outlook_appointment_scheduling_assistant.main:run"
train = "microsoft_outlook_appointment_scheduling_assistant.main:train"
replay = "microsoft_outlook_appointment_scheduling_assistant.main:replay"
test = "microsoft_outlook_appointment_scheduling_assistant.main:test"
run_with_trigger = "microsoft_outlook_appointment_scheduling_assistant.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
