name: Execute Agenda Crew

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  execute-crew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # test connections
      - name: Test Connection
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python test_connection.py
      #test connections
      - name: Run CrewAI
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OUTLOOK_ACCESS_TOKEN: ${{ secrets.OUTLOOK_ACCESS_TOKEN }}
          WHATSAPP_ACCESS_TKN: ${{ secrets.WHATSAPP_ACCESS_TKN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          RECIPIENT_PHONE_NUMBER: ${{ secrets.RECIPIENT_PHONE_NUMBER }}
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python src/asistente_agenda/main.py